name: Construir APK Control Avicola

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Configurar Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: "8.9"

      - name: Extraer proyecto
        run: run: gradle assembleDebug -Pkotlin.jvm.target.validation.mode=warning
          mkdir proyecto
          unzip -q ControlAvicola_proyecto_mejorado.zip -d proyecto

      - name: Construir APK
        working-directory: proyecto
        run: gradle assembleDebug

      - name: Guardar APK
        uses: actions/upload-artifact@v4
        with:
          name: Control-Avicola-APK
          path: proyecto/app/build/outputs/apk/debug/app-debug.apk
